name: Deployment
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        working-directory: saveforlater-backend
        run: docker build -t my-app:latest .

      - name: Stop Existing Containers
        working-directory: saveforlater-backend
        run: docker compose down

      - name: Start Containers
        working-directory: saveforlater-backend
        run: docker compose up -d

      # - name: Build Docker Image
      #   working-directory: simple-node-app
      #   run: |
      #     echo "Building Docker image..."
      #     docker build -t node-app .
      #     if [ $? -ne 0 ]; then
      #       echo "Docker build failed"
      #       exit 1
      #     fi

      # - name: Stop Existing Containers
      #   working-directory: simple-node-app
      #   run: |
      #     echo "Stopping existing containers..."
      #     docker compose down
      #     if [ $? -ne 0 ]; then
      #       echo "Failed to stop existing containers"
      #       exit 1
      #     fi

      # - name: Start Containers
      #   working-directory: simple-node-app
      #   run: |
      #     echo "Starting containers..."
      #     docker compose up -d
      #     if [ $? -ne 0 ]; then
      #       echo "Failed to start containers"
      #       exit 1
      #     fi

      - name: Wait for containers to start
        run: |
          echo "Waiting for 10 seconds to allow the containers to start..."
          sleep 10  # Wait for the containers to fully start before checking

      - name: Check if application is running
        working-directory: simple-node-app
        run: |
          echo "Checking if application is accessible..."
          curl -f http://localhost:3000  # Use the -f flag to fail silently on HTTP errors
          if [ $? -ne 0 ]; then
            echo "Application is not accessible"
            exit 1
          fi
          echo "Application is accessible"
