name: Deployment
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        working-directory: simple-node-app
        run: |
          echo "Building Docker image..."
          docker build -t node-app .
          if [ $? -ne 0 ]; then
            echo "Docker build failed"
            exit 1
          fi

      - name: Stop Existing Containers
        working-directory: simple-node-app
        run: |
          echo "Stopping existing containers..."
          docker compose down
          if [ $? -ne 0 ]; then
            echo "Failed to stop existing containers"
            exit 1
          fi

      - name: Start Containers
        working-directory: simple-node-app
        run: |
          echo "Starting containers..."
          docker compose up -d
          if [ $? -ne 0 ]; then
            echo "Failed to start containers"
            exit 1
          fi

      - name: check
        working-directory: simple-node-app
        run: |
          curl http://localhost:3000
